server:
  port: 8080
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user
    username: Administrator
    password: a1652790B
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true